#### Libraries

In [11]:
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

#### Data

In [26]:
df = pd.read_csv(f"Dataset\ecommerce_fraud_dataset.csv")
df_u = df.copy()

In [19]:
display(df)
print(f'jumlah row: {df.shape[0]}\njumlah column: {df.shape[1]}')

,Transaction_ID,Transaction_Amount,Quantity,Customer_Age,Account_Age_Days,Transaction_Hour,Product_Category,Payment_Method,Device_Used,Address_Match,Is_Fraud,Customer_ID,Transaction_Time,Previous_Transactions_Count,Failed_Transaction_Attempts,Fraud_Label,Fraud_Reason
0,100000,140.78,5,32,107,7,Books,Credit Card,Mobile,Yes,0,CUST100000,2026-02-10 15:58:43,38,4,0,Normal Transaction
1,100001,50.89,3,40,331,10,Groceries,UPI,Laptop,Yes,0,CUST100001,2026-01-20 20:14:43,28,3,0,Normal Transaction
2,100002,275.72,3,39,309,1,Luxury,Credit Card,Tablet,No,1,CUST100002,2026-02-28 19:33:43,14,2,1,Suspicious Device
3,100003,836.87,2,38,161,11,Electronics,Credit Card,Laptop,Yes,0,CUST100003,2026-01-23 13:05:43,42,3,0,Normal Transaction
4,100004,2.13,1,44,59,9,Groceries,PayPal,Mobile,Yes,0,CUST100004,2026-01-22 00:11:43,7,2,0,Normal Transaction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,129995,213.44,2,55,368,14,Electronics,Debit Card,Tablet,No,0,CUST129995,2025-12-31 00:10:43,46,1,0,Normal Transaction
29996,129996,638.15,2,34,381,9,Groceries,PayPal,Tablet,No,1,CUST129996,2026-02-23 00:19:43,5,4,1,Location Mismatch
29997,129997,379.93,2,50,883,5,Electronics,Debit Card,Laptop,Yes,0,CUST129997,2026-01-27 07:33:43,27,0,0,Normal Transaction
29998,129998,357.57,3,22,833,10,Luxury,Credit Card,Mobile,No,0,CUST129998,2026-01-01 07:54:43,29,1,0,Normal Transaction
29999,129999,304.45,1,52,970,17,Electronics,Credit Card,Mobile,Yes,0,CUST129999,2026-02-09 02:59:43,26,0,0,Normal Transaction

jumlah row: 30000
jumlah column: 17

In [24]:
df.info()
display(df.describe())
display(df.describe(include=['O']))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Transaction_ID               30000 non-null  int64
 1   Transaction_Amount           30000 non-null  float64
 2   Quantity                     30000 non-null  int64
 3   Customer_Age                 30000 non-null  int64
 4   Account_Age_Days             30000 non-null  int64
 5   Transaction_Hour             30000 non-null  int64
 6   Product_Category             30000 non-null  object
 7   Payment_Method               30000 non-null  object
 8   Device_Used                  30000 non-null  object
 9   Address_Match                30000 non-null  object
 10  Is_Fraud                     30000 non-null  int64
 11  Customer_ID                  30000 non-null  object
 12  Transaction_Time             30000 non-null  object
 13  Previous_Transactions_Count  30000 non-null  int64
 14  Failed_Transaction_Attempts  30000 non-null  int64
 15  Fraud_Label                  30000 non-null  int64
 16  Fraud_Reason                 30000 non-null  object
dtypes: float64(1), int64(9), object(7)
memory usage: 3.9+ MB

,Transaction_ID,Transaction_Amount,Quantity,Customer_Age,Account_Age_Days,Transaction_Hour,Is_Fraud,Previous_Transactions_Count,Failed_Transaction_Attempts,Fraud_Label
count,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000
mean,114999.500000,298.667502,2.997033,38.500367,500.782467,11.522100,0.437533,24.492833,2.014667,0.437533
std,8660.398374,295.227523,1.417918,12.099328,289.122262,6.920162,0.496091,14.406818,1.415928,0.496091
min,100000.000000,0.000000,1.000000,18.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,107499.750000,88.500000,2.000000,28.000000,250.000000,6.000000,0.000000,12.000000,1.000000,0.000000
50%,114999.500000,209.170000,3.000000,38.000000,503.000000,12.000000,0.000000,24.000000,2.000000,0.000000
75%,122499.250000,413.265000,4.000000,49.000000,752.000000,18.000000,1.000000,37.000000,3.000000,1.000000
max,129999.000000,2590.400000,5.000000,59.000000,999.000000,23.000000,1.000000,49.000000,4.000000,1.000000

,Product_Category,Payment_Method,Device_Used,Address_Match,Customer_ID,Transaction_Time,Fraud_Reason
count,30000,30000,30000,30000,30000,30000,30000
unique,5,4,3,2,30000,25989,5
top,Electronics,Credit Card,Tablet,Yes,CUST100000,2025-12-30 08:10:43,Normal Transaction
freq,6084,7600,10078,15023,1,4,19618

- Need to know the time range of the data
- Need to know the data distribution
- Then analyze the data

In [35]:
## convert object to timestamp
df_u["Transaction_Time"] = pd.to_datetime(df_u["Transaction_Time"])
rtime = df_u['Transaction_Time'].describe()
display(rtime)
print(f'range time: {rtime['min']} - {rtime['max']}')

count                            30000
mean     2026-01-27 16:40:16.872000256
min                2025-12-23 23:43:43
25%                2026-01-10 10:03:28
50%                2026-01-27 16:29:43
75%                2026-02-14 00:17:13
max                2026-03-03 10:13:43
Name: Transaction_Time, dtype: object

range time: 2025-12-23 23:43:43 - 2026-03-03 10:13:43